# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AIDetection
                                 A QGIS plugin
 Using deep learning to detect interested block 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-30
        copyright            : (C) 2021 by GDOU
        email                : 2270514313@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AIDetection class from file AIDetection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .AI_Detection import AIDetection
    return AIDetection(iface)
